### ISSUE TITLE
No error,  just doesn't encode after starting.  I suspect it can't write to SDCard?  

### ISSUE THREAD

**Issue by ronester** [brarcher/video-transcoder#114]
So I was trying to encode a clip that's on my SDCard so I could convert it into a GIF in another app, but it would not give me an error message even after several minutes.  I'm only guessing that it can't write to the card; only has read access.  Is it possible to add an output directory so I could point the new file to internal storage in the next release?  

Samsung J7 with Android 7.0

**Comment by licaon-kter** [comment]
It saves in Movies, that's not read-only, right?

**Comment by ronester** [comment]
Unless it's trying to save to Movies folder on the SD card.. ?  Like I said, it gives no error at all so I don't even know if that's the issue.  It was just a guess.

**Comment by brarcher** [comment]
It saves in Movies for videos/gifs and Music for audio. That should be writable. I think if it were unable to write data it would give an error fairly quickly.

Depending on the options and the size of the file, I have seen ffmpeg process a file for a bit before writing anything out. If you are making a gif clip out of a big video, ffmpeg will need to navigate to the correct spot then start encoding. I've seen that take some time. In your case, do you see the progress bar advance? I wonder if it just did not make it to the target part of the file yet.

When the encoding is finished, it will post a message saying where the file is, and give you an option to share it directly.

**Comment by ronester** [comment]
Ah OK, I understand.  The progress bar doesn't "progress", the whole thing stays spinning gray but I've only given it 5 minutes before giving up.  I was trying to cut in at 50 minute mark on a movie clip (encoded in x264/aac) and the length I wanted is only about 20 seconds.  

I'll play with it again and give it more time as your suggest.  Thanks for replying!

**Comment by brarcher** [comment]
That sounds about right. When the encoding starts I do not know how long it will take, so I wait for status updates from ffmpeg. When it is scanning a file to know where to start it does not give any feedback. Only once it is actually doing the encoding will it give a progress indicator.

Let me know if by waiting longer the encoding ultimately fails, or after a very long time it gets stuck. If that happens, re-open this please.
