### ISSUE TITLE
Can't Join the Indonesian Translation Team

### ISSUE THREAD

**Issue by ditokp** [brarcher/video-transcoder#132]
Hello, after I make request about Indonesian translation on Transifex, I can't join the Indonesian translation team. This is the screenshot:

![screenshot from 2018-09-07 18-38-07](https://user-images.githubusercontent.com/27815899/45217203-69ed4f80-b2cd-11e8-86dc-61c4edb64bb0.png)

is me make mistake?

Note: I'm sorry if my English is bad

**Comment by brarcher** [comment]
Hi! I logged into Transifex and saw your join request. It is now accepted, and you should be OK. Transifex does not always send me emails on requests (not sure why) so I did not see your request right away.

Thanks for poking me. Let me know if you run into any other issues.

**Comment by ditokp** [comment]
Hello, thank you very much
