### ISSUE TITLE
Request for acceptance of the Italian translation on Transifex

### ISSUE THREAD

**Issue by 6og** [brarcher/video-transcoder#136]
I have seen from a previous closed issue that not always the translation requests are forwarded. I already have the translated XML ready, but I'm too much of a lazy noob to do a pull request on GitHub.
P.S.
This string seems missing from other translated XMLs:
<string name=""invalidMediaFile"">The Selected media file is invalid or not supported</string>

**Comment by brarcher** [comment]
I found your request on Transifex and approved it. If you need to send another request to become a translator for the project, let me know and I can approve it as well.

> This string seems missing from other translated XMLs:
<string name=""invalidMediaFile"">The Selected media file is invalid or not supported

It might be that the string has not been translated by anyone else yet. All the translations are from volunteers.

**Comment by 6og** [comment]
Thank you.
I sent the request.
