### ISSUE TITLE
WebM not supported

### ISSUE THREAD

**Issue by dwroland** [brarcher/video-transcoder#146]
"The selected media file is invalid or not supported" error.

**Comment by licaon-kter** [comment]
Ok and? Get some media info, get the logcat...details matter....where's the fi

**Comment by dwroland** [comment]
I'm trying to create log but it's not simple at my device. I will probably do it later with other phone.

**Comment by brarcher** [comment]
The app should have support for WebM now, as that was added back in October last year (https://github.com/brarcher/video-transcoder/pull/139). If you are seeing that it does not work, please provide some logs and details so it can be investigated.

**Comment by dwroland** [comment]
I checked with pure webm file and app works fine. So there is problem with source files. I guess app detect file as damaged when source webm file doesn't contain video or audio track (I want convert webm with only sound to mp3).

**Comment by brarcher** [comment]
Hm. I'm seeing that the WebM file's I'm trying to load into the app cannot be previewed. I think that the Android video player does not support WebM playback. As a result, the app gives up on the file. The app could probably do better by letting the user still encode to another format and ignore the video preview.

**Comment by dwroland** [comment]
Weird because I can preview video. Check this example: https://track6.mixtape.moe/ejeznk.webm 
And this is example with only sound: https://my.mixtape.moe/xdoimk.webm

**Comment by brarcher** [comment]
I tried the two examples you posted. I confirmed that on the currently release the video+audio one loads correctly but the audio-only one does not. With the changes I posted in https://github.com/brarcher/video-transcoder/pull/147 the audio file does now load correctly. I think that the codecs were not always being parsed from ffprobe correctly, and this should be improved in the next release.

I'll create a new release soon so you can try it out and get back to encoding. (:

**Comment by brarcher** [comment]
A beta of v0.14 is now available on Google Play which includes a fix for this. Give it a try and give me any feedback you may have.

https://play.google.com/apps/testing/protect.videoeditor

**Comment by dwroland** [comment]
Fixed :). Encoding for webm audio-only and video-only now works fine.

Btw. add play/pause button for preview in future if it's possible.

**Comment by brarcher** [comment]
>add play/pause button for preview in future if it's possible.

Yeah, I hear ya. It is silly that I have not done that yet. (:  The request is captured in https://github.com/brarcher/video-transcoder/issues/135.
