### ISSUE TITLE
[Privacy] WebView

### ISSUE THREAD

**Issue by duggalsu** [brarcher/video-transcoder#175]
Opt out of sending metrics to Google when using WebView. Add the following to the manifest -
```
<meta-data android:name="android.webkit.WebView.MetricsOptOut" android:value="true" />
```
https://developer.android.com/guide/webapps/webview-privacy

**Comment by duggalsu** [comment]
Are you sure that it is not the app that uploads the data but the Android System WebView (which has full internet access) ?

**Comment by licaon-kter** [comment]
Where exactly is that used?

**Comment by duggalsu** [comment]
I'm not very sure but I believe the data collection refers to the App usage data uploaded to the Google account if enabled.

**Comment by licaon-kter** [comment]
Not what I've asked.


In this app, were, were is it used?

Can you show a network report (eg. Netguard) of webview connecting to the internet while using this app?

**Comment by duggalsu** [comment]
I will not be able to test this currently but wanted to be sure if this was an issue without the app having internet permissions. I will close this for now until I find out more or am able to test it.

**Comment by brarcher** [comment]
The webview is used to display an About dialog. It renders an HTML page that is included with the app. FYI
