### ISSUE TITLE
Cannot load video from extern sd card on Android 7.1

### ISSUE THREAD

**Issue by java-py-c-cpp-js** [brarcher/video-transcoder#27]
Error message: Failed to resolve the location of media file
It seems like it's nessesary to use the media framework API for loading from extern sd card. If ffmpeg needs direct access to the file and can't use the framework, maybe your app could automatically copy the video to intern storage for editing.

**Comment by travisfw** [comment]
I (and, I would guess, many others) store video to the external SD by default. I was really happy to find this app this morning, but this issue is a big deal.

**Comment by brarcher** [comment]
I'm not sure where you are observing the issue. My device does not have an external SD card, which is probably why I did not see this myself. Are you seeing this when initially selecting a file, or when encoding a file? Could you attach logs when you hit the issue?

There are two parts to the app. The first uses a VideoView to preview the video. The second uses FFmpeg to encode the video. The FFmpeg part would not use the Media Framework APIs as it handles the encoding itself. If you are seeing the issue when first selecting the media file, perhaps the app is not handling that properly. Hopefully I can better diagnose the issue if I can see logs.

**Comment by phuyuk** [comment]
Same error on Lineage 13. "Failed to resolve..."

**Comment by brarcher** [comment]
It turns out the issue was getting the absolute file path from whatever arbitrary Activity starts when showing a file browser. To simplify matters, I've incorporated a file browser into the app itself. I was able to reproduce the failure on an emulator and find that using the built-in file browser resolves the issue.

Would anyone be able to confirm that the following version does resolve the issue?
[video-transcoder.apk.zip](https://github.com/brarcher/video-transcoder/files/1769711/app-release.apk.zip)

**Comment by brarcher** [comment]
I've not heard any feedback, so I'll move forward with the change.

**Comment by utack** [comment]
Does not work for me unfortunately  
The file browser goes directly to /storage/emulated/0 (aka internal sdcard), and I have no way to switch to external SD

**Comment by brarcher** [comment]
Oh, OK. I see that the file picker can configure where the root directory is, and if it is not specified it defaults to:

Environment.getExternalStorageDirectory()

In your case, what is your external SD card directory? Maybe there are multiple paths, and this happens to just pick one.

**Comment by utack** [comment]
in my case /storage/A04F-08E4
"ExternalStorage" sounds like the virtual internal sdcard?

**Comment by brarcher** [comment]
I've found a different embedded file picker which first asks which storage to use, then allows a file to be selected from that storage. On the emulator I now see with this that there are multiple storage options (internal and sd card) and can pick between the two. I'll incorporate that embedded file picker and cut a new release.

**Comment by brarcher** [comment]
[V0.4](https://github.com/brarcher/video-transcoder/releases/tag/v0.4) was is now available, which should resolve this issue. If it still does not work, or does not work as expected, please re-open.
