### ISSUE TITLE
Add VP8 support (webm)

### ISSUE THREAD

**Issue by floppyD** [brarcher/video-transcoder#29]
An option to limit the output size would be great too.

**Comment by brarcher** [comment]
If someone is interested in contributing VP8 support (if I do not get to it) the following needs to be done:
- Add an entry to the [MediaContainer](https://github.com/brarcher/video-transcoder/blob/master/app/src/main/java/protect/videotranscoder/media/MediaContainer.java) enum, as well as any relevant codecs to the [VideoCodec](https://github.com/brarcher/video-transcoder/blob/master/app/src/main/java/protect/videotranscoder/media/VideoCodec.java) and [AudioCodec](https://github.com/brarcher/video-transcoder/blob/master/app/src/main/java/protect/videotranscoder/media/AudioCodec.java) enums.
-  Ensure that the version of FFmpeg used support decoding and encoding the webm format.
