### ISSUE TITLE
Support setting FPS to "same as source"

### ISSUE THREAD

**Issue by Cogitri** [brarcher/video-transcoder#30]
Thanks for the nice application, however I prefer to keep the transcoded video at the same FPS count as the original one. Would it be possible to implement such an option?

**Comment by brarcher** [comment]
It may not be intuitive, but when a media file is selected its current values are determined and set as the default encode values. It should be that the FPS (and other properties) are set to that of the source file. If for some reason the values could not be determined then it falls back to a canned default value.

Are you finding that the source file's FPS value is not being set to the default value, nor is it available in the FPS list?

**Comment by Cogitri** [comment]
Oh, sorry, I actually didn't notice that and just searched for said option ( as other transcoders such as handbrake have it ). Thanks for making me aware of that behavior :)
