### ISSUE TITLE
app does not encode some videos.

### ISSUE THREAD

**Issue by shirou-jeff** [brarcher/video-transcoder#39]
#### Expected behavior

the user can encode any video from this app.

#### Actual behavior

the user can not encode any video from this app.

#### How to reproduce

- Download the application. 
- Starts. 
- Try to encode some MP4 video. 
- After this, The application throws an error and stops the encoding of the desired video.

* Browser: video transcoder V 0.4
* Operating system:android 5.1.1

#### Recording Of The Bug

https://youtu.be/W3c5ir_UrPI
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@shirou-jeff/app-does-not-encode-some-videos">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by brarcher** [comment]
Watching the video, I'm a little confused. The video shows that the application successfully saved the audio of the video as an MP3. Later is started converting the video to FLV format, then reports that the encoding was canceled. The button presses are not highlighted, so it is not clear if the encoding was canceled because the "Cancel" button was pressed. Was that button pressed? If so, that is expected behavior. If not, can you reproduce with button clicks visible so it is most clear? Additionally, also include logs.

**Comment by brarcher** [comment]
An Android 5.1 the screen touches will be visible when enabling the Show Touches option under Developer Options:

![image](https://user-images.githubusercontent.com/5264535/36946276-57256ba4-1f88-11e8-83ff-dcae85edb3c6.png)

**Comment by shirou-jeff** [comment]
Greetings, in answer to your question. No, the Cancel button was not pressed. The encoding was cancelled by itself, I would gladly upload a video where it shows the touches on the device screen.

how can I show you whit a video?

**Comment by brarcher** [comment]
Interesting. Could you capture the logs when you reproduce this and attach them so I can see what is going on internally? At the top of the Developer Options there may be an option for Take Bug Report. Some of that data may be sensitive, so if you could just attach the logs around the time the app is encoding and failing, it would help me.

**Comment by shirou-jeff** [comment]
Excuse me, can you explain more in detail how to do that? I'd be happy to help you. I'll do everything I can.

**Comment by brarcher** [comment]
There are a few options available for grabbing logs. The first is to connect the Android phone to a computer and use the debugging tool ``adb``. [Here](https://live.paloaltonetworks.com/t5/Learning-Articles/How-to-Collect-Logs-logcat-from-an-Android-Phone/ta-p/57918) is information on how to do that on Windows. [Here](https://www.citrix.com/blogs/2015/06/02/mobility-experts-how-to-collect-android-device-logs-for-troubleshooting-xenmobile-issues/) is an alternative. Linux and Mac are similar.

If you want to capture a bug report (which contains logs and additional data) you can do so through the Developer Options menu in Android. [Here](https://developer.android.com/studio/debug/bug-report.html) are details on how to go that route.

Does that help?

**Comment by shirou-jeff** [comment]
Yes, perfect. I'll do it. When I have the results I will be writing here.

**Comment by brarcher** [comment]
I was able to reproduce this myself. It appears that the mechanism I use in Android to background the processing times out and cancels the encoding:

```
03-19 22:21:37.734 14025 14025 D VideoTranscoder: JOB_PROGRESS_MSG: 12
03-19 22:21:37.962   595   595 I JobServiceContext: Client timed out while executing (no jobFinished received). sending onStop. fdd69cc #u0a123/1 protect.videoeditor/protect.videotranscoder.service.FFmpegProcessService
03-19 22:21:37.988 14025 14025 I VideoTranscoder: on stop job: 1
03-19 22:21:37.994 14025 14025 D VideoTranscoder: Attempt to cancel FFmpeg: success
03-19 22:21:38.019 14025 14025 D VideoTranscoder: Job complete, result: false
03-19 22:21:38.019 14025 14025 D VideoTranscoder: Encode result: false
03-19 22:21:38.191 14025 14025 I VideoTranscoder: Service destroyed
```

**Comment by shirou-jeff** [comment]
I apologize for not reproducing the error myself. So this is something happening only on my device?

**Comment by brarcher** [comment]
If it is the same error, then no it is not only your device. I found on my Android 7 device that after 10 minutes Android will cancel the job. It may be that a number of users are encoding files which can be completed before then, so they never notice the limit.

Fixing this should be easy enough. I'll look into using a normal background service for processing instead of the job mechanism.

**Comment by brarcher** [comment]
I added a change which should resolve this. After the change I was able to successfully process a file which took over 2 hours on my phone. Before it would be canceled after 10 minutes. If the fix in the next release does not resolve your issue, please re-open.

**Comment by shirou-jeff** [comment]
perfect, i will update and test the new version.
