### ISSUE TITLE
Using as audio transcoder: allow mp3 m4a ogg files as input

### ISSUE THREAD

**Issue by k3b** [brarcher/video-transcoder#47]
video-transcoder and ffmpeg can also transcode audio-only files.

For video-transcoder i have to rename the audio file "someAudio.m4a" to "someAudio.m4a.avi" to allow converting to mp3.

I would be nice if video-transcoder also accept audio file names mp3 m4a ogg

**Comment by brarcher** [comment]
That is easy enough to do. Presently the application will filter on supported video files. I expanded it to also allow audio files, and it appears to work just fine. I'll make that change.

**Comment by brarcher** [comment]
This will be available in the next release. Thanks for the suggestion.

**Comment by k3b** [comment]
thankyou very much
