### ISSUE TITLE
don't force portrait mode

### ISSUE THREAD

**Issue by treakiandroid** [brarcher/video-transcoder#49]
On a phone its ok, but on a tablet or even desktop/convertible that's supposed to stand and not to be holdn by hand its quitecbad to forcecthe portrait mode. Please use the sensor/fixed mode as given from the system and dont be one out of a few app that annoys users by forcing portrait mode needlessly on such a big screen (and even not on a little (your able of scrolling i guess)

Thanks.

Forcing a mode should be dedicated to games only

Thanks

**Comment by brarcher** [comment]
Thanks for the suggestion. The next release will allow screen rotating.
