### ISSUE TITLE
Suggestion: Create "Movies" directory when it doesn't exist

### ISSUE THREAD

**Issue by celsoazevedo** [brarcher/video-transcoder#58]
Hey,

Just installed this app and it's working very well. Clean UI, no ads, free, easy enough to use. Good job!

I noticed that the app returns this error when the "Movies" directory doesn't exist ([screenshot](https://www.celsoazevedo.com/files/2018/Screenshot_Video_Transcoder_20180324-185039.png)):

> Encoding failed: /storage/emulated/0/Movies/Video_Transcoder_Output.mp4: No such file or directory

I was able to start the encoding process after manually creating the Movies folder, but maybe the app could do this instead of returning an error?

Also, and since we can't choose a new name for encoded file, perhaps file names should have a different name. For example, "original-file-name-video-resolution.mp4" instead of "Video_Transcoder_Output.mp4".

**Comment by brarcher** [comment]
Good suggestions. I'll add some changes to address your two points.

**Comment by brarcher** [comment]
The changes have been merged. Let me know if it does not work as you expect in the next release.
