### ISSUE TITLE
proposal logo for Video Transcoder app

### ISSUE THREAD

**Issue by ammarraisafti** [brarcher/video-transcoder#92]
Hi admin, I want to offer a new logo design is more sweet and simple application for Video Transcoder, If you like and can accept it.

You can simply reply to this proposal, I will gladly send you a new logo this file and I was able to provide some variation for this app, thank you!
![dadadadda](https://user-images.githubusercontent.com/37721970/41176259-eeec1ef4-6b89-11e8-88ed-cb51eeaeccf1.png)

**Comment by brarcher** [comment]
Hi! There is another issue open for a better logo. You can find that here: https://github.com/brarcher/video-transcoder/issues/57

You are welcome to reply there and give feedback on the icon which is in the process of being integrated.
