### ISSUE TITLE
Edit your Transifex team name

### ISSUE THREAD

**Issue by licaon-kter** [brarcher/video-transcoder#97]
...it's shown as `N/A` in the drop down menu now

**Comment by brarcher** [comment]
I think I messed it up when I created the account. It asked for a company name and I though "there is no company, I'll put N/A". Little did I know that the value would be used in the URL and other places...

I see there is a way to change it after the fact. The name is now updated to "Protect". I can also update the URL, but if I do that it would need to happen when I can update the links on the GItHub pages at the same time.
